packaging_format = 2

id = "minecraft_bedrock"
name = "Minecraft Bedrock Server"
description.en = "Three-dimensional sandbox construction game"

version = "1.21.0.03~ynh1"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64"]
multi_instance = false

disk = "100M"
ram.build = "50M"
ram.runtime = "500M"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.0.03.zip"
        sha256 = "66d035a4a756dd95f5242e395d637f27d8ef7c356677e6e234482a4f90d565c8"
        in_subdir = false
        extract = true

    [resources.ports]
    main.default = 19132
    main.exposed = "UDP"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
