packaging_format = 2

id = "minecraft_bedrock"
name = "Minecraft Bedrock Server"
description.en = "Three-dimensional sandbox construction game"

version = "1.21.3.01~ynh1"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64"]
multi_instance = false

disk = "100M"
ram.build = "50M"
ram.runtime = "500M"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.3.01.zip"
        sha256 = "eb1ce77d53b883e2028158b1c0ced1aeb9a854c9459db205c160edd6461fbe73"
        in_subdir = false
        extract = true

    [resources.ports]
    main.default = 19132
    main.exposed = "UDP"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
